# SPDX-FileCopyrightText: 2026 paintress-team
# SPDX-License-Identifier: GPL-3.0-or-later

"""Paintress wire protocol: generated Python bindings.

DO NOT EDIT. Generated by paintress_protocol_gen from schema/protocol.yaml.
protocol 0.1.0   wire_id 0x0001
"""

from __future__ import annotations

import enum
import struct
from dataclasses import dataclass
from typing import ClassVar

PROTOCOL_VERSION = "0.1.0"
WIRE_ID = 0x0001

# --- Constants --------------------------------------------------------------
START_BYTE = 0xAA
HEADER_SIZE = 0x04
CRC_SIZE = 0x02
MAX_PAYLOAD_SIZE = 0x100

class MessageType(enum.IntEnum):
    COMMAND = 0x01
    DATA = 0x02
    ACK = 0x03
    NACK = 0x04
    EVENT = 0x05
    LOG = 0x06

class Command(enum.IntEnum):
    BEGIN_SWATH = 0x01
    END_SWATH = 0x02
    ARM = 0x03
    ABORT = 0x04
    GET_STATUS = 0x05
    RESET = 0x06
    PURGE = 0x07
    IDENTIFY = 0x0C

class Event(enum.IntEnum):
    PRINT_STARTED = 0x01
    PRINT_COMPLETE = 0x02
    PRINT_ERROR = 0x03
    TRIGGER_TIMEOUT = 0x04

class ErrorCode(enum.IntEnum):
    OK = 0x00
    UNKNOWN_CMD = 0x01
    INVALID_PARAM = 0x02
    NO_SLOT_AVAILABLE = 0x03
    SWATH_NOT_FOUND = 0x04
    SWATH_NOT_READY = 0x05
    PRINT_IN_PROGRESS = 0x06
    SLOT_BUSY = 0x07
    LINE_COUNT_MISMATCH = 0x08
    VERSION_MISMATCH = 0x09
    PROFILE_MISMATCH = 0x0A
    DAC_LATCHED = 0x0C

class SlotState(enum.IntEnum):
    EMPTY = 0x00
    RECEIVING = 0x01
    READY = 0x02
    PRINTING = 0x03

class LogLevel(enum.IntEnum):
    DEBUG = 0x00
    INFO = 0x01
    WARN = 0x02
    ERROR = 0x03

@dataclass
class BeginSwathParams:
    swath_id: int
    line_count: int

    _STRUCT: ClassVar[struct.Struct] = struct.Struct("<HI")
    SIZE: ClassVar[int] = 6

    def pack(self) -> bytes:
        return self._STRUCT.pack(self.swath_id, self.line_count)

    @classmethod
    def unpack(cls, data: bytes) -> "BeginSwathParams":
        _f = cls._STRUCT.unpack_from(data)
        return cls(_f[0], _f[1])

@dataclass
class ArmParams:
    swath_id: int
    line_delay_us: int

    _STRUCT: ClassVar[struct.Struct] = struct.Struct("<HH")
    SIZE: ClassVar[int] = 4

    def pack(self) -> bytes:
        return self._STRUCT.pack(self.swath_id, self.line_delay_us)

    @classmethod
    def unpack(cls, data: bytes) -> "ArmParams":
        _f = cls._STRUCT.unpack_from(data)
        return cls(_f[0], _f[1])

@dataclass
class PurgeParams:
    channel_mask_id: int
    pulses: int

    _STRUCT: ClassVar[struct.Struct] = struct.Struct("<BB")
    SIZE: ClassVar[int] = 2

    def pack(self) -> bytes:
        return self._STRUCT.pack(self.channel_mask_id, self.pulses)

    @classmethod
    def unpack(cls, data: bytes) -> "PurgeParams":
        _f = cls._STRUCT.unpack_from(data)
        return cls(_f[0], _f[1])

@dataclass
class IdentifyResponse:
    wire_id: int
    profile_hash: int
    fw_build: int
    boot_flags: int

    _STRUCT: ClassVar[struct.Struct] = struct.Struct("<HIIB")
    SIZE: ClassVar[int] = 11

    def pack(self) -> bytes:
        return self._STRUCT.pack(self.wire_id, self.profile_hash, self.fw_build, self.boot_flags)

    @classmethod
    def unpack(cls, data: bytes) -> "IdentifyResponse":
        _f = cls._STRUCT.unpack_from(data)
        return cls(_f[0], _f[1], _f[2], _f[3])

@dataclass
class BeginSwathResponse:
    swath_id: int
    slot: int

    _STRUCT: ClassVar[struct.Struct] = struct.Struct("<HB")
    SIZE: ClassVar[int] = 3

    def pack(self) -> bytes:
        return self._STRUCT.pack(self.swath_id, self.slot)

    @classmethod
    def unpack(cls, data: bytes) -> "BeginSwathResponse":
        _f = cls._STRUCT.unpack_from(data)
        return cls(_f[0], _f[1])

@dataclass
class EndSwathResponse:
    swath_id: int
    complete: int

    _STRUCT: ClassVar[struct.Struct] = struct.Struct("<HB")
    SIZE: ClassVar[int] = 3

    def pack(self) -> bytes:
        return self._STRUCT.pack(self.swath_id, self.complete)

    @classmethod
    def unpack(cls, data: bytes) -> "EndSwathResponse":
        _f = cls._STRUCT.unpack_from(data)
        return cls(_f[0], _f[1])

@dataclass
class StatusResponse:
    slot_a_state: SlotState
    slot_a_swath_id: int
    slot_a_lines_received: int
    slot_b_state: SlotState
    slot_b_swath_id: int
    slot_b_lines_received: int
    receiving: int
    printing: int
    dac_latched: int

    _STRUCT: ClassVar[struct.Struct] = struct.Struct("<BHIBHIBBB")
    SIZE: ClassVar[int] = 17

    def pack(self) -> bytes:
        return self._STRUCT.pack(int(self.slot_a_state), self.slot_a_swath_id, self.slot_a_lines_received, int(self.slot_b_state), self.slot_b_swath_id, self.slot_b_lines_received, self.receiving, self.printing, self.dac_latched)

    @classmethod
    def unpack(cls, data: bytes) -> "StatusResponse":
        _f = cls._STRUCT.unpack_from(data)
        return cls(SlotState(_f[0]), _f[1], _f[2], SlotState(_f[3]), _f[4], _f[5], _f[6], _f[7], _f[8])

@dataclass
class AckPayload:
    command: int
    data: bytes

    _STRUCT: ClassVar[struct.Struct] = struct.Struct("<B")

    def pack(self) -> bytes:
        return self._STRUCT.pack(self.command) + self.data

    @classmethod
    def unpack(cls, data: bytes) -> "AckPayload":
        _f = cls._STRUCT.unpack_from(data)
        return cls(_f[0], data[cls._STRUCT.size:])

@dataclass
class NackPayload:
    command: int
    error: ErrorCode

    _STRUCT: ClassVar[struct.Struct] = struct.Struct("<BB")
    SIZE: ClassVar[int] = 2

    def pack(self) -> bytes:
        return self._STRUCT.pack(self.command, int(self.error))

    @classmethod
    def unpack(cls, data: bytes) -> "NackPayload":
        _f = cls._STRUCT.unpack_from(data)
        return cls(_f[0], ErrorCode(_f[1]))

@dataclass
class LogPayload:
    level: LogLevel
    text: bytes

    _STRUCT: ClassVar[struct.Struct] = struct.Struct("<B")

    def pack(self) -> bytes:
        return self._STRUCT.pack(int(self.level)) + self.text

    @classmethod
    def unpack(cls, data: bytes) -> "LogPayload":
        _f = cls._STRUCT.unpack_from(data)
        return cls(LogLevel(_f[0]), data[cls._STRUCT.size:])
