# SPDX-FileCopyrightText: 2026 paintress-team
# SPDX-License-Identifier: GPL-3.0-or-later

"""Hardware test: the daemon's double-buffer pipeline against a real board.

Wires SerialManager + SwathHandler + PrintPipeline to a flashed firmware and
checks that load() pre-streams TWO swaths into the two PSRAM slots concurrently
(the overlap that lets swath N+1 be ready while N prints), holding the third
until a slot frees. Usage: python hw_tests/pipeline_hw_test.py [COMx]
"""
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import serial.tools.list_ports as list_ports
from paintress_daemon.serial_manager import SerialManager
from paintress_daemon.swath_handler import SwathHandler
from paintress_daemon.print_pipeline import PrintPipeline
from paintress_daemon.head_profiles import BYTES_PER_LINE
from paintress_daemon.protocol import SlotState


def pick_port(argv):
    if len(argv) > 1:
        return argv[1]
    for p in list_ports.comports():
        if p.device != "COM1":
            return p.device
    raise SystemExit("No board serial port found")


def fake_swath(n_lines):
    # No job is loaded here, so the line size is the frame's: every head the
    # firmware serves rides the same generated BYTES_PER_LINE.
    return [bytes((i + b) & 0xFF for b in range(BYTES_PER_LINE)) for i in range(n_lines)]


def main():
    port = pick_port(sys.argv)
    print(f"Opening {port} ...")
    sm = SerialManager(port, baudrate=2000000)
    if not sm.connect():
        raise SystemExit("connect failed")

    handler = SwathHandler(sm)
    sm.set_frame_callback(handler.handle_frame)
    sm.set_raw_callback(lambda d: None)
    time.sleep(0.3)

    # RESET is a chip reboot: the ACK arrives, then the link
    # drops and the board re-enumerates. Reopen the port before continuing.
    handler.reset()
    sm.disconnect()
    print("reset -> board rebooting; reopening the port ...")
    time.sleep(3.0)
    sm = SerialManager(port, baudrate=2000000)
    if not sm.connect():
        raise SystemExit("reconnect after reset failed")
    handler = SwathHandler(sm)
    sm.set_frame_callback(handler.handle_frame)
    sm.set_raw_callback(lambda d: None)
    time.sleep(0.3)

    pipeline = PrintPipeline(
        lambda sid, lines: handler.send_swath(sid, lines).success,
        lambda sid, line_delay_us: handler.print_swath(sid, line_delay_us).success,
    )

    swaths = [(1, fake_swath(8)), (2, fake_swath(8)), (3, fake_swath(8))]
    print("load() -> pipeline pre-streams into the double buffer ...")
    pipeline.load(swaths)
    time.sleep(2.0)

    status = handler.get_status()
    print("status:", status)

    ok = True
    if status is None:
        print("  NO STATUS"); ok = False
    else:
        a, b = status["slot_a"], status["slot_b"]
        # Both slots should be READY, holding swaths 1 and 2.
        ready_ids = {a["swath_id"], b["swath_id"]} if (
            a["state"] == SlotState.READY and b["state"] == SlotState.READY) else set()
        print(f"  slot_a: state={a['state']} swath={a['swath_id']} lines={a['lines_received']}")
        print(f"  slot_b: state={b['state']} swath={b['swath_id']} lines={b['lines_received']}")
        if ready_ids == {1, 2}:
            print("  OK: both slots filled (swaths 1 & 2 ready, 3 held) -> double-buffer overlap works")
        else:
            print("  FAIL: expected both slots READY with swaths {1, 2}")
            ok = False
        if pipeline.is_failed():
            print("  FAIL: pipeline reported a streaming failure"); ok = False

    pipeline.stop()
    sm.disconnect()
    print("\n" + ("DONE OK" if ok else "DONE FAIL"))
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
